"""add address and phone to clients, add user_id

Revision ID: b09221249810
Revises: 92a53382215c
Create Date: 2025-05-27 12:51:20.980577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09221249810'
down_revision: Union[str, None] = '92a53382215c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('clients', sa.Column('address', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'clients', ['user_id'])
    op.create_foreign_key(None, 'clients', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'updated_at')
    op.drop_column('clients', 'address')
    op.drop_column('clients', 'user_id')
    # ### end Alembic commands ###
